### PR TITLE
Adds media_player

### PR DESCRIPTION
**Pull request by ejonesnospam**
Absolutely love the functionality so far, so I spent a couple nights to add a little more. This adds a media_player option, which provides source and volume controls. 

Below is a new code request for hisensetv.py in the API. Are these keys specifically available? If not, I could still perform the actions, but it would require more complexity.

    @_check_connected
    def send_key_vol_up(self):
        """ Sends a keypress of the volume up key to the TV. """
        self._send_key("KEY_VOL_UP")

    @_check_connected
    def send_key_vol_down(self):
        """ Sends a keypress of the volume down key to the TV. """
        self._send_key("KEY_VOL_DOWN")

FUTURE:
Also, I'm trying to add a generic service to send any available command to the tv (such as menu buttons or navigation), but I'm stumped so far. I've created the services (in a different code version), but when executed, an error about referenced entities is logged. I'm sure I'll figure it out soon ;)

### CODE REVIEW

**Comment by newAM** [comment]
Wow!  This looks amazing!  I'll try it out this weekend!

For those keys, I previously found a list of possible keys from this other API: https://github.com/BVMiko/hisense-udp/blob/master/hisense.py

The magic string might be "KEY_VOLUMEUP" and "KEY_VOLUMEDOWN" if the different APIs are consistent.

**Comment by ejonesnospam** [comment]
API Qs:

- I don’t see that the (OK/ENTER/Select) key has been added? It looks like it’s the following for me. Can you add this too? "KEY_OK"

- Previous API request, appended:

@_check_connected
def send_key_ok(self):
    """ Sends a keypress of the OK key to the TV. """
    self._send_key("KEY_OK”)

@_check_connected
def send_key_volume_up(self):
    """ Sends a keypress of the volume up key to the TV. """
    self._send_key("KEY_VOLUMEUP")

@_check_connected
def send_key_vol_down(self):
    """ Sends a keypress of the volume down key to the TV. """
    self._send_key("KEY_VOLUMEDOWN")


Personal Experience
- I have no need for the media playback controls (for now). Commands for play/pause seemed to be rather non-functional for me. I was able to pause the content on my connected FireTV, but the play button did not resume playback. Instead, the OK button was required. Perhaps this is specific to each connected device? Any preference or thoughts?

Usage 

- I've managed to get the send_command function to work. Steps have been incorporated into the readme. I'll be uploaded new changes into my pull request shortly.

- Delay of 5 to 15 seconds is observed when power is toggled, due to ping response time action and wait period. In other words, when you turn the power off, the switch flips back to on (on its own, for a short time, until an update is completed and the off status is determined. Do you see this as well, or it it just my network configuration? If you see this as well, this (as all things) can be remedied. I presume this code change means that the command will be inferred to work correctly, while an issue with the command would take more time before error or user detection. The reason I bring this up, is that it’s a software design decision. Just wanted to get your input.

**Comment by newAM** [comment]
Added the extra keys to the backend, and pushed a release to pypi, it's at 0.0.5 now.

> I have no need for the media playback controls (for now). Commands for play/pause seemed to be rather non-functional for me. I was able to pause the content on my connected FireTV, but the play button did not resume playback. Instead, the OK button was required. Perhaps this is specific to each connected device? Any preference or thoughts?

Could be per-device, for unofficial API hijacking I usually take the road of assume it works for everything until someone makes a bug report.

> I've managed to get the send_command function to work. Steps have been incorporated into the readme. I'll be uploaded new changes into my pull request shortly.

I just checked it out, there's some rendering issues with the readme (it uses [reStructuredText](https://docutils.sourceforge.io/docs/user/rst/quickref.html) instead of markdown), but other than that looks good!

> Delay of 5 to 15 seconds is observed when power is toggled, due to ping response time action and wait period. In other words, when you turn the power off, the switch flips back to on (on its own, for a short time, until an update is completed and the off status is determined. Do you see this as well, or it it just my network configuration? If you see this as well, this (as all things) can be remedied. I presume this code change means that the command will be inferred to work correctly, while an issue with the command would take more time before error or user detection. The reason I bring this up, is that it’s a software design decision. Just wanted to get your input.

I have this too, it was done out of pure laziness, I just copied the home-assistant WOL switch to create this.

**Comment by ejonesnospam** [comment]
I've finished the playback controls, and uploaded a new pull request for the API. 
Native volume control (up and down) in the API would not work for me, but that is likely model specific. For my model, everything works except mute. I've added a new config option that defines which button is used for playback resume after pause, which would be one of "play", "pause", or "ok".
Still trying to nail down a bug in the media_player that relates to zeroconf and ssdp. Once I find the issue, I'll update again

**Comment by ejonesnospam** [comment]
I think I have it all running with no issues. Once the api has the media commands, it should all work for you, as well. Please feel free to download and test. Look forward to hearing about your usage.

**Comment by ejonesnospam** [comment]
Well, just when I thought it might be working, something goes off the rails. I assume an automated update to my H9 has actually changed the ping response when the TV is off. Now, the TV always indicates ON, since a ping timeout never occurs. After resetting the TV back to factory defaults, ping now responses as previously. I'll start work on another config option for switch and media_player when I can.

**Comment by ejonesnospam** [comment]
Closing due to lack of input from author

**Comment by newAM** [comment]
Sorry, my email filters started coalescing update notifications for this - I just saw this going through my git inbox, want to reopen and I'll take a look tomorrow?

**Comment by lindsaymarkward** [comment]
@ejonesnospam @newAM - can we keep going with this? Looks like some great work was done and then not finished off.
I'd really like to be able to use this to change the source on my TV in a script. Thanks 👍

**Comment by ejonesnospam** [comment]
You're welcome to pursue further development with a fork. Due to lack of interest, I've moved on.

**Comment by newAM** [comment]
@ejonesnospam 's repo is available here: https://github.com/ejonesnospam/hisensetv_hass, I believe HACS allows you to use any repository.

Unfortunately my interest in this has diminished as well.  Over time I found that my TV would drop the Ethernet connection and require physical unplug/replugging of either AC power or the Ethernet jack about once a week.  I ended up using a pi connected to my TV as an HDMI CEC server, which has been far more reliable for power controls.

**Pull request closed without merging**
